-- =============================================================
-- MULTI-STORE ACCOUNTING & P&L SUITE - SUPABASE CLOUD SCHEMA
-- =============================================================
-- Run this in Supabase SQL Editor (Project: qsmigegcefcbohmufywh)

-- 1. STORE SALES TABLE (ยอดขายประจำวัน 3 ร้าน)
CREATE TABLE IF NOT EXISTS public.store_sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    store_name TEXT NOT NULL,
    channel TEXT NOT NULL DEFAULT 'Cash', -- Cash, QR/Transfer, Credit, Delivery, Other
    amount NUMERIC NOT NULL DEFAULT 0,
    note TEXT,
    period TEXT, -- Format: YYYY-MM (e.g. 2026-03)
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. STORE EXPENSES TABLE (รายจ่าย 4 แหล่งเงินทุน)
CREATE TABLE IF NOT EXISTS public.store_expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    store_name TEXT NOT NULL DEFAULT 'All / Central',
    category TEXT NOT NULL DEFAULT 'วัตถุดิบ/สต็อก',
    payer TEXT NOT NULL DEFAULT 'Churntawan', -- Nantaporn, Thayakorn, Churntawan, Kanthong, กองกลางร้าน
    amount NUMERIC NOT NULL DEFAULT 0,
    slip_url TEXT,
    note TEXT,
    period TEXT, -- Format: YYYY-MM (e.g. 2026-03)
    status TEXT DEFAULT 'Settled', -- Pending, Settled, Reimbursed
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. STORE SETTINGS TABLE (ตั้งค่าระบบและรายชื่อร้านค้า)
CREATE TABLE IF NOT EXISTS public.store_settings (
    id TEXT PRIMARY KEY,
    setting_value JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 4. ENABLE ROW LEVEL SECURITY (RLS)
ALTER TABLE public.store_sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.store_expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.store_settings ENABLE ROW LEVEL SECURITY;

-- 5. POLICIES: ALLOW ANON ACCESS (MATCHES SIGNATURE PAYROLL SETUP)
DROP POLICY IF EXISTS "Allow all on store_sales" ON public.store_sales;
CREATE POLICY "Allow all on store_sales" ON public.store_sales FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all on store_expenses" ON public.store_expenses;
CREATE POLICY "Allow all on store_expenses" ON public.store_expenses FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all on store_settings" ON public.store_settings;
CREATE POLICY "Allow all on store_settings" ON public.store_settings FOR ALL USING (true) WITH CHECK (true);

-- 6. INDEXES FOR FAST QUERYING BY DATE & PERIOD
CREATE INDEX IF NOT EXISTS idx_store_sales_date ON public.store_sales (date);
CREATE INDEX IF NOT EXISTS idx_store_sales_period ON public.store_sales (period);
CREATE INDEX IF NOT EXISTS idx_store_sales_store ON public.store_sales (store_name);
CREATE INDEX IF NOT EXISTS idx_store_expenses_date ON public.store_expenses (date);
CREATE INDEX IF NOT EXISTS idx_store_expenses_period ON public.store_expenses (period);
CREATE INDEX IF NOT EXISTS idx_store_expenses_payer ON public.store_expenses (payer);

-- 7. DEFAULT STORE SETTINGS SEED
INSERT INTO public.store_settings (id, setting_value)
VALUES (
    'general',
    '{
        "stores": ["ร้านชวนตะวัน (Churntawan)", "สาขาที่ 2 (Branch 2)", "สาขาที่ 3 (Branch 3)"],
        "payers": ["Nantaporn", "Thayakorn", "Churntawan", "Kanthong", "กองกลางร้าน (Store Cash)"],
        "channels": ["เงินสด (Cash)", "โอนเงิน / สแกน QR", "บัตรเครดิต", "เดลิเวอรี (Grab/Lineman)"],
        "categories": [
            "วัตถุดิบและสต็อกสินค้า (Ingredients/Stock)",
            "ค่าเช่าสถานที่ (Rent)",
            "สาธารณูปโภค ค่าน้ำ/ค่าไฟ (Utilities)",
            "บรรจุภัณฑ์และของใช้สิ้นเปลือง (Packaging/Supplies)",
            "ซ่อมบำรุงและงานช่าง (Maintenance)",
            "ค่าขนส่งและเดินทาง (Logistics)",
            "การตลาดและโฆษณา (Marketing)",
            "เบ็ดเตล็ดและค่าใช้จ่ายทั่วไป (Miscellaneous)"
        ]
    }'::jsonb
)
ON CONFLICT (id) DO NOTHING;
